### ISSUE TITLE
keyerror when makemigrations is applied

### ISSUE THREAD

**Issue by bharathsanjay** [djunicode/DJ-Comps-Skill-Finder#35]
how do i handle this? this occurs when i apply makemigrations
 File "C:\Users\LENOVO.000\DJ-Comps-Skill-Finder\env\lib\os.py", line 673, in __getitem__
    raise KeyError(key) from None
KeyError: 'SECRET_KEY'

**Comment by viral98** [comment]
Hey Sanjay! Apologies but this repository is no longer maintained!
However, just looking at the error maybe this could be of use to you https://help.pythonanywhere.com/pages/environment-variables-for-web-apps/
